arb-dir: lib/l10n
template-arb-file: app_en_GB.arb
output-class: AppLocalizations
output-dir: lib/l10n
synthetic-package: false
nullable-getter: false
required-resource-attributes: false
preferred-supported-locales:
  - en_GB