name: recipe_vault
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Image selection and compression
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2

  # ✅ Routing
  go_router: ^15.2.4

  # ✅ Networking
  http: ^1.2.1

  # ✅ Firebase Core + Storage (needed for image uploads)
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true