name: recipe_vault
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ───── UI & Icons ─────
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_speed_dial: ^7.0.0
  reorderables: ^0.5.0
  palette_generator: ^0.3.3

  # ───── Routing ─────
  go_router: ^13.2.5
  uni_links: ^0.5.1

  # ───── Image Handling ─────
  image_picker: ^1.0.4
  flutter_image_compress: ^1.1.0
  image_cropper: ^5.0.0
  path_provider: ^2.1.2

  # ───── State & Utilities ─────
  provider: ^6.1.2
  http: ^1.2.1
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.5

  # ───── Sharing & Output ─────
  share_plus: ^7.2.2
  pdf: ^3.10.4
  printing: ^5.12.0

  # ───── Firebase ─────
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  cloud_functions: ^5.6.0
  firebase_storage: ^12.4.8
  firebase_app_check: ^0.3.2+9

  # ───── Authentication ─────
  google_sign_in: ^6.2.1

  # ───── Local Storage ─────
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ───── RevenueCat In-App Purchases ─────
  purchases_flutter: ^8.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/recipe_vault_appLogo.png
    - assets/icon/recipe_vaultBG.png
    - assets/icon/round_vaultLogo.png

flutter_launcher_icons:
  image_path: assets/icon/recipe_vault_appLogo.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F6F4FA"
  image: assets/icon/recipe_vaultBG.png
  android: true
  ios: true
  fullscreen: true