name: recipe_vault
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+23

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ───── UI & Icons ─────
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_speed_dial: ^7.0.0
  reorderables: ^0.5.0
  palette_generator: ^0.3.3
  google_fonts: ^6.1.0

  # ───── Routing ─────
  uni_links: ^0.5.1
  intl: ^0.20.2

  # ───── Image Handling ─────
  image_picker: ^1.0.4
  flutter_image_compress: ^1.1.0
  image_cropper: ^5.0.0
  path_provider: ^2.1.2

  # ───── State & Utilities ─────
  provider: ^6.1.2
  http: ^1.2.1
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  cached_network_image: ^3.3.1

  # ───── Sharing & Output ─────
  share_plus: ^7.2.2
  pdf: ^3.10.4
  printing: ^5.12.0

  # ───── Firebase ─────
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  cloud_functions: ^5.6.0
  firebase_storage: ^12.4.8
  firebase_app_check: ^0.3.2+9
  firebase_messaging: ^15.2.9
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10

  # ───── Authentication ─────
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

  # ───── Local Storage ─────
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ───── RevenueCat In-App Purchases ─────
  purchases_flutter: ^8.10.5
  collection: ^1.19.1

  # ───── Multi-language Support ─────
  flutter_localizations:
    sdk: flutter
  # Once you create `lib/l10n/*.arb` files, run `flutter gen-l10n` and add:
  # flutter_gen:
  #   integrations:
  #     l10n: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/recipe_vault_appLogo.png
    - assets/icon/recipe_vaultBG.png
    - assets/icon/round_vaultLogo.png
    - assets/icon/lock_icon.png
    - assets/icon/cheeky_badger_round.png

flutter_launcher_icons:
  image_path: assets/icon/recipe_vault_appLogo.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F6F4FA"
  image: assets/icon/lock_icon.png
  android: true
  ios: true
  fullscreen: true

  # Localization config (optional, but tidy)
  # l10n:
  #   arb-dir: lib/l10n
  #   template-arb-file: app_en_GB.arb
  #   output-dir: lib/l10n/generated
  #   output-localization-file: app_localizations.dart
  #   preferred-supported-locales:
  #     - en_GB