// lib/main.dart
import 'package:flutter/foundation.dart'
    show kIsWeb, kReleaseMode; // ← ensure kReleaseMode
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';

import 'package:recipe_vault/app/app_bootstrap.dart';
import 'package:recipe_vault/app/recipe_vault_app.dart';

import 'package:recipe_vault/auth/auth_service.dart';
import 'package:recipe_vault/billing/subscription_service.dart';
import 'package:recipe_vault/core/language_provider.dart';
import 'package:recipe_vault/core/text_scale_notifier.dart';
import 'package:recipe_vault/core/theme_notifier.dart';
import 'package:recipe_vault/features/recipe_vault/vault_view_mode_notifier.dart';

// Use the options generated by `flutterfire configure`
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1) Initialize Firebase exactly once
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 2) App Check — prod in release, debug providers in debug
  await FirebaseAppCheck.instance.activate(
    appleProvider: kReleaseMode
        ? AppleProvider.appAttestWithDeviceCheckFallback
        : AppleProvider.debug, // ← iOS debug
    androidProvider: kReleaseMode
        ? AndroidProvider.playIntegrity
        : AndroidProvider.debug, // ← Android debug
    webProvider: kIsWeb
        ? ReCaptchaV3Provider(
            const String.fromEnvironment(
              'RECAPTCHA_V3_SITE_KEY',
              defaultValue: '',
            ),
          )
        : null,
  );

  // 3) App‑level bootstrap (prefs, Hive boxes, caches, etc.)
  await AppBootstrap.ensureReady();

  // 4) Run app with eagerly‑initialized services
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeNotifier()),
        ChangeNotifierProvider(create: (_) => TextScaleNotifier()),
        ChangeNotifierProvider(create: (_) => LanguageProvider()),
        ChangeNotifierProvider(
          create: (_) => VaultViewModeNotifier()..loadFromPrefs(),
        ),
        // Eager: subs service so navigation guards & paywall have it ready
        ChangeNotifierProvider<SubscriptionService>(
          lazy: false,
          create: (_) => SubscriptionService()..init(),
        ),
        Provider(create: (_) => AuthService()),
      ],
      child: const RecipeVaultApp(),
    ),
  );
}
